env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
settings:
  react:
    version: detect
ignorePatterns:
  - package.json
  - package-lock.json
  - babel.config.js
rules:
  no-unused-vars: "off"
  "@typescript-eslint/no-unused-vars": error
